--==============================
-- SEE ALL WAREHOUSE
--==============================

SHOW WAREHOUSES

--==============================
-- CREATE WAREHOUSES 
--==============================

-- DATA INJESTION

CREATE OR REPLACE WAREHOUSE POC_INJESTION_WAREHOUSE
WITH
WAREHOUSE_SIZE = SMALL
AUTO_SUSPEND = 180
AUTO_RESUME = TRUE
COMMENT = 'FOR DATA INJESTION';

-- FOR PIPES

CREATE OR REPLACE WAREHOUSE POC_PIPE_WAREHOUSE
WITH
WAREHOUSE_SIZE = SMALL
AUTO_SUSPEND = 180
AUTO_RESUME = TRUE
COMMENT = 'FOR SNOWPIPE';

-- FOR DYNAMIC TABLES

CREATE OR REPLACE WAREHOUSE POC_DYNAMIC_TABLE_WAREHOUSE
WITH
WAREHOUSE_SIZE = SMALL
AUTO_SUSPEND = 180
AUTO_RESUME = TRUE
COMMENT = 'FOR SNOWPIPE';

-- FOR DBT / DATA TRANSFORMATION

CREATE OR REPLACE WAREHOUSE POC_TRANSFORM_WAREHOUSE
WITH
WAREHOUSE_SIZE = SMALL
AUTO_SUSPEND = 180
AUTO_RESUME = TRUE
COMMENT = 'FOR DATA TRANSFORMATION';

-- FOR DBEAVER / ADHOC QUERIES

CREATE OR REPLACE WAREHOUSE POC_ADHOC_WAREHOUSE
WITH
WAREHOUSE_SIZE = SMALL
AUTO_SUSPEND = 180
AUTO_RESUME = TRUE
COMMENT = 'FOR ADHOC QUERY PORPOSE';

--==============================
-- DROP AND VERIFY
--==============================

DROP WAREHOUSE IF EXISTS POC_AIRBYTE_INJESTION;

SHOW WAREHOUSES;

ALTER WAREHOUSE POC_TRANSFORM_WAREHOUSE SUSPEND;
