
USE DATABASE FINANCE_DB;

--===============================
-- SHOW STEAMS  
--===============================

USE SCHEMA LANDING;

SHOW STREAMS IN SCHEMA LANDING;

--===============================
-- CREATE STREAMS
--===============================

-->> STEAMS ON TRANSACTIONS

CREATE STREAM IF NOT EXISTS LANDING.TRANSACTIONS_STREAM 
ON TABLE POSTGRES_RAW.TRANSACTIONS;

--

SELECT SYSTEM$STREAM_HAS_DATA('LANDING.TRANSACTIONS_STREAM');
SELECT TOP 10 * FROM LANDING.TRANSACTIONS_STREAM;


--->> STEAMS ON FUND_HOLDINGS

CREATE STREAM IF NOT EXISTS LANDING.FUND_HOLDINGS_STREAM 
ON TABLE POSTGRES_RAW.FUND_HOLDINGS;

--
SELECT SYSTEM$STREAM_HAS_DATA('LANDING.FUND_HOLDINGS_STREAM');
SELECT TOP 10 * FROM LANDING.FUND_HOLDINGS_STREAM;


--->> STEAMS ON ACCOUNT_BALANCES

CREATE STREAM IF NOT EXISTS LANDING.ACCOUNT_BALANCES_STREAM 
ON TABLE POSTGRES_RAW.ACCOUNT_BALANCES;

--
SELECT SYSTEM$STREAM_HAS_DATA('LANDING.ACCOUNT_BALANCES_STREAM');
SELECT TOP 10 * FROM LANDING.ACCOUNT_BALANCES_STREAM;

--===============================
-- END OF THE DOUMENT
--===============================

