
USE DATABASE FINANCE_DB;

--==============================
-- SHOW TABLES
--==============================

USE SCHEMA LANDING;

SHOW VIEWS;

SELECT * 
FROM INFORMATION_SCHEMA.VIEWS 
WHERE VIEW_DEFINITION IS NOT NULL 
AND TABLE_SCHEMA = 'LANDING';

--==============================
-- CREATE TABLES
--==============================

-----------------------
-- VW INVESTORS
-----------------------

CREATE OR REPLACE SECURE VIEW LANDING.VW_INVESTORS
AS
SELECT *
FROM POSTGRES_RAW.INVESTORS

--

DESC VIEW LANDING.VW_INVESTORS;

SELECT GET_DDL('VIEW', 'VW_INVESTORS');

SELECT TOP 10 * FROM LANDING.VW_INVESTORS;

-----------------------
-- VW ACCOUNTS
-----------------------

CREATE OR REPLACE SECURE VIEW LANDING.VW_ACCOUNTS
AS
SELECT *
FROM POSTGRES_RAW.ACCOUNTS

--

DESC VIEW LANDING.VW_ACCOUNTS;

SELECT GET_DDL('VIEW', 'VW_INVESTORS');

SELECT TOP 10 * FROM LANDING.VW_ACCOUNTS;


-----------------------
-- VW TRANSACTIONS
-----------------------

CREATE OR REPLACE SECURE VIEW LANDING.VW_TRANSACTIONS
AS
SELECT *
FROM POSTGRES_RAW.TRANSACTIONS

--

DESC VIEW LANDING.VW_TRANSACTIONS;

SELECT GET_DDL('VIEW', 'VW_TRANSACTIONS');

SELECT TOP 10 * FROM LANDING.VW_TRANSACTIONS;


-----------------------
-- VW FUND_HOLDINGS
-----------------------

CREATE OR REPLACE SECURE VIEW LANDING.VW_FUND_HOLDINGS
AS
SELECT *
FROM POSTGRES_RAW.FUND_HOLDINGS

--

DESC VIEW LANDING.VW_FUND_HOLDINGS;

SELECT GET_DDL('VIEW', 'VW_FUND_HOLDINGS');

SELECT TOP 10 * FROM LANDING.VW_FUND_HOLDINGS;


-----------------------
-- VW ACCOUNT_BALANCES
-----------------------

CREATE OR REPLACE SECURE VIEW LANDING.VW_ACCOUNT_BALANCES
AS
SELECT *
FROM POSTGRES_RAW.ACCOUNT_BALANCES

--

DESC VIEW LANDING.VW_ACCOUNT_BALANCES;

SELECT GET_DDL('VIEW', 'VW_ACCOUNT_BALANCES');

SELECT TOP 10 * FROM LANDING.VW_ACCOUNT_BALANCES;


-----------------------
-- VW FUNDS
-----------------------

CREATE OR REPLACE SECURE VIEW LANDING.VW_FUNDS
AS
SELECT *
FROM POSTGRES_RAW.FUNDS

--

DESC VIEW LANDING.VW_FUNDS;

SELECT GET_DDL('VIEW', 'VW_FUNDS');

SELECT TOP 10 * FROM LANDING.VW_FUNDS;


-----------------------
-- VW FUND_MANAGERS
-----------------------

CREATE OR REPLACE SECURE VIEW LANDING.VW_FUND_MANAGERS
AS
SELECT *
FROM POSTGRES_RAW.FUND_MANAGERS

--

DESC VIEW LANDING.VW_FUND_MANAGERS;

SELECT GET_DDL('VIEW', 'VW_FUND_MANAGERS');

SELECT TOP 10 * FROM LANDING.VW_FUND_MANAGERS;


-----------------------
-- VW NAV_DATA
-----------------------

CREATE OR REPLACE SECURE VIEW LANDING.VW_NAV_DATA
AS
SELECT *
FROM GCS_RAW.NAV_DATA

--

DESC VIEW LANDING.VW_NAV_DATA;

SELECT GET_DDL('VIEW', 'VW_NAV_DATA');

SELECT TOP 10 * FROM LANDING.VW_NAV_DATA;


-----------------------
-- VW FUND_METADATA
-----------------------

CREATE OR REPLACE SECURE VIEW LANDING.VW_FUND_METADATA
AS
SELECT *
FROM GCS_RAW.FUND_METADATA

--

DESC VIEW LANDING.VW_FUND_METADATA;

SELECT GET_DDL('VIEW', 'VW_FUND_METADATA');

SELECT TOP 10 * FROM LANDING.VW_FUND_METADATA;

-----------------------
-- VW MARKET_DATA
-----------------------

CREATE OR REPLACE SECURE VIEW LANDING.VW_MARKET_DATA
AS
SELECT *
FROM GCS_RAW.MARKET_DATA

--

DESC VIEW LANDING.VW_MARKET_DATA;

SELECT GET_DDL('VIEW', 'VW_MARKET_DATA');

SELECT TOP 10 * FROM LANDING.VW_MARKET_DATA;


-----------------------
-- VW MARKET_DATA
-----------------------

CREATE OR REPLACE SECURE VIEW LANDING.VW_RATINGS_DATA
AS
SELECT *
FROM GCS_RAW.RATINGS_DATA

--

DESC VIEW LANDING.VW_RATINGS_DATA;

SELECT GET_DDL('VIEW', 'VW_RATINGS_DATA');

SELECT TOP 10 * FROM LANDING.VW_RATINGS_DATA;







