--===============================
-- SHOW DATABASES 
--===============================

SHOW DATABASES;

SHOW SCHEMAS;

--===============================
-- CREATE ROLE FOR DBT
--===============================

-- ROLE
CREATE ROLE IF NOT EXISTS DBT_TRANSFORM_ROLE; 

-- WAREHOUSE
GRANT USAGE ON WAREHOUSE POC_TRANSFORM_WAREHOUSE TO DBT_TRANSFORM_ROLE;

-- DATABASE
GRANT USAGE ON DATABASE FINANCE_DB TO DBT_TRANSFORM_ROLE;

-- SCHEMA - LANDING
GRANT USAGE ON SCHEMA LANDING TO DBT_TRANSFORM_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA LANDING TO DBT_TRANSFORM_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA LANDING TO DBT_TRANSFORM_ROLE;

-- DBT SCHEMAS
GRANT ALL ON SCHEMA STAGING TO ROLE DBT_TRANSFORM_ROLE;
GRANT ALL ON SCHEMA INTERMEDIATE TO ROLE DBT_TRANSFORM_ROLE;
GRANT ALL ON SCHEMA ANALYTICS TO ROLE DBT_TRANSFORM_ROLE;

--===============================
-- END OF THE DOCUMENT
--===============================





