
--===============================
-- SHOW DATABASES
--===============================

SHOW DATABASES;
SHOW SCHEMAS;

--===============================
-- CREATE ROLE FOR DBT
--===============================

USE ROLE ACCOUNTADMIN;

-- Create role
CREATE ROLE IF NOT EXISTS DBT_TRANSFORM_ROLE;

-- Grant role to user
GRANT ROLE DBT_TRANSFORM_ROLE TO USER rahulraj;

--===============================
-- WAREHOUSE PERMISSIONS
--===============================

GRANT USAGE ON WAREHOUSE POC_TRANSFORM_WAREHOUSE TO ROLE DBT_TRANSFORM_ROLE;
GRANT OPERATE ON WAREHOUSE POC_TRANSFORM_WAREHOUSE TO ROLE DBT_TRANSFORM_ROLE;

--===============================
-- DATABASE PERMISSIONS
--===============================

GRANT USAGE ON DATABASE FINANCE_DB TO ROLE DBT_TRANSFORM_ROLE;
GRANT MONITOR ON DATABASE FINANCE_DB TO ROLE DBT_TRANSFORM_ROLE;

--===============================
-- LANDING SCHEMA (READ-ONLY)
--===============================

GRANT USAGE ON SCHEMA FINANCE_DB.LANDING TO ROLE DBT_TRANSFORM_ROLE;

-- Grant SELECT on existing objects
GRANT SELECT ON ALL VIEWS IN SCHEMA FINANCE_DB.LANDING TO ROLE DBT_TRANSFORM_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA FINANCE_DB.LANDING TO ROLE DBT_TRANSFORM_ROLE;

-- Grant SELECT on future objects (for new views/tables added later)
GRANT SELECT ON FUTURE VIEWS IN SCHEMA FINANCE_DB.LANDING TO ROLE DBT_TRANSFORM_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FINANCE_DB.LANDING TO ROLE DBT_TRANSFORM_ROLE;

--===============================
-- STAGING SCHEMA (FULL ACCESS)
--===============================

GRANT USAGE ON SCHEMA FINANCE_DB.STAGING TO ROLE DBT_TRANSFORM_ROLE;

-- CREATE privileges (THIS WAS MISSING!)
GRANT CREATE TABLE ON SCHEMA FINANCE_DB.STAGING TO ROLE DBT_TRANSFORM_ROLE;
GRANT CREATE VIEW ON SCHEMA FINANCE_DB.STAGING TO ROLE DBT_TRANSFORM_ROLE;
GRANT CREATE STAGE ON SCHEMA FINANCE_DB.STAGING TO ROLE DBT_TRANSFORM_ROLE;

-- Modify/Delete privileges on existing objects
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA FINANCE_DB.STAGING TO ROLE DBT_TRANSFORM_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA FINANCE_DB.STAGING TO ROLE DBT_TRANSFORM_ROLE;

-- Ownership on future objects (dbt will create and own them)
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA FINANCE_DB.STAGING TO ROLE DBT_TRANSFORM_ROLE;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN SCHEMA FINANCE_DB.STAGING TO ROLE DBT_TRANSFORM_ROLE;

--===============================
-- INTERMEDIATE SCHEMA (FULL ACCESS)
--===============================

GRANT USAGE ON SCHEMA FINANCE_DB.INTERMEDIATE TO ROLE DBT_TRANSFORM_ROLE;

-- CREATE privileges
GRANT CREATE TABLE ON SCHEMA FINANCE_DB.INTERMEDIATE TO ROLE DBT_TRANSFORM_ROLE;
GRANT CREATE VIEW ON SCHEMA FINANCE_DB.INTERMEDIATE TO ROLE DBT_TRANSFORM_ROLE;
GRANT CREATE STAGE ON SCHEMA FINANCE_DB.INTERMEDIATE TO ROLE DBT_TRANSFORM_ROLE;

-- Future objects
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA FINANCE_DB.INTERMEDIATE TO ROLE DBT_TRANSFORM_ROLE;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN SCHEMA FINANCE_DB.INTERMEDIATE TO ROLE DBT_TRANSFORM_ROLE;

--===============================
-- ANALYTICS SCHEMA (FULL ACCESS)
--===============================

GRANT USAGE ON SCHEMA FINANCE_DB.ANALYTICS TO ROLE DBT_TRANSFORM_ROLE;

-- CREATE privileges
GRANT CREATE TABLE ON SCHEMA FINANCE_DB.ANALYTICS TO ROLE DBT_TRANSFORM_ROLE;
GRANT CREATE VIEW ON SCHEMA FINANCE_DB.ANALYTICS TO ROLE DBT_TRANSFORM_ROLE;
GRANT CREATE STAGE ON SCHEMA FINANCE_DB.ANALYTICS TO ROLE DBT_TRANSFORM_ROLE;
GRANT CREATE MATERIALIZED VIEW ON SCHEMA FINANCE_DB.ANALYTICS TO ROLE DBT_TRANSFORM_ROLE;

-- Future objects
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA FINANCE_DB.ANALYTICS TO ROLE DBT_TRANSFORM_ROLE;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN SCHEMA FINANCE_DB.ANALYTICS TO ROLE DBT_TRANSFORM_ROLE;

--===============================
-- VERIFY GRANTS
--===============================

-- Check user grants
SHOW GRANTS TO USER rahulraj;

-- Check role grants
SHOW GRANTS TO ROLE DBT_TRANSFORM_ROLE;

-- Check schema-specific grants
SHOW GRANTS ON SCHEMA FINANCE_DB.STAGING;
SHOW GRANTS ON SCHEMA FINANCE_DB.INTERMEDIATE;
SHOW GRANTS ON SCHEMA FINANCE_DB.ANALYTICS;

--===============================
-- END OF THE DOCUMENT
--===============================
