
USE DATABASE FINANCE_DB;

--==============================
-- SHOW TABLES
--==============================

USE SCHEMA GCS_RAW;

SHOW TABLES;

--==============================
-- CREATE TABLES
--==============================


----------------------------------
-->> LANDING TABLES FROM POSTGRES
----------------------------------

USE SCHEMA POSTGRES_RAW

-->> INVESTORS

CREATE OR REPLACE TRANSIENT TABLE POSTGRES_RAW.INVESTORS 
	(
    INVESTOR_ID NUMBER AUTOINCREMENT,
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    EMAIL VARCHAR(255),
    PHONE VARCHAR(20),
    DATE_OF_BIRTH DATE,
    REGISTRATION_DATE DATE DEFAULT CURRENT_DATE,
    KYC_STATUS VARCHAR(20),
    RISK_PROFILE VARCHAR(20),
    CUSTOMER_SEGMENT VARCHAR(20),
    ADDRESS_LINE1 VARCHAR(255),
    ADDRESS_LINE2 VARCHAR(255),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    POSTAL_CODE VARCHAR(20),
    COUNTRY VARCHAR(50),
    IS_ACTIVE BOOLEAN,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
    
    -- Metadata columns
    SOURCE_FILE_NAME               VARCHAR(500),
    SOURCE_FILE_ROW_NUMBER         NUMBER,
    FILE_CONTENT_KEY               VARCHAR(500),
    FILE_LAST_MODIFIED_TIMESTAMP   TIMESTAMP_NTZ,
    LOAD_TIMESTAMP                 TIMESTAMP_NTZ,
    LOAD_SOURCE                    VARCHAR(100)
	);


-->> FUND MANAGERS

CREATE OR REPLACE TRANSIENT TABLE POSTGRES_RAW.FUND_MANAGERS 
	(
    MANAGER_ID NUMBER,
    MANAGER_CODE VARCHAR(20),
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    EMAIL VARCHAR(255),
    YEARS_EXPERIENCE INT,
    EDUCATION VARCHAR(255),
    SPECIALIZATION VARCHAR(100),
    IS_ACTIVE BOOLEAN,
    HIRE_DATE DATE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
    
    -- Metadata columns
    SOURCE_FILE_NAME               VARCHAR(500),
    SOURCE_FILE_ROW_NUMBER         NUMBER,
    FILE_CONTENT_KEY               VARCHAR(500),
    FILE_LAST_MODIFIED_TIMESTAMP   TIMESTAMP_NTZ,
    LOAD_TIMESTAMP                 TIMESTAMP_NTZ,
    LOAD_SOURCE                    VARCHAR(100)
	);

-->> FUNDS

CREATE OR REPLACE TRANSIENT TABLE POSTGRES_RAW.FUNDS 
	(
    FUND_ID NUMBER AUTOINCREMENT,
    FUND_CODE VARCHAR(20),
    FUND_NAME VARCHAR(255),
    FUND_CATEGORY VARCHAR(50),
    FUND_TYPE VARCHAR(20),
    MANAGER_ID NUMBER,
    INCEPTION_DATE DATE,
    EXPENSE_RATIO NUMBER(5,4),
    MINIMUM_INVESTMENT NUMBER(15,2),
    AUM_MILLIONS NUMBER(15,2),
    BENCHMARK_INDEX VARCHAR(100),
    IS_ACTIVE BOOLEAN,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
    
    -- Metadata columns
    SOURCE_FILE_NAME               VARCHAR(500),
    SOURCE_FILE_ROW_NUMBER         NUMBER,
    FILE_CONTENT_KEY               VARCHAR(500),
    FILE_LAST_MODIFIED_TIMESTAMP   TIMESTAMP_NTZ,
    LOAD_TIMESTAMP                 TIMESTAMP_NTZ,
    LOAD_SOURCE                    VARCHAR(100)
	);

-->> ACCOUNTS

CREATE OR REPLACE TRANSIENT TABLE POSTGRES_RAW.ACCOUNTS 
	(
    ACCOUNT_ID NUMBER AUTOINCREMENT,
    ACCOUNT_NUMBER VARCHAR(20),
    INVESTOR_ID NUMBER,
    ACCOUNT_TYPE VARCHAR(20),
    ACCOUNT_STATUS VARCHAR(20),
    OPENING_DATE DATE,
    CLOSING_DATE DATE,
    TOTAL_BALANCE NUMBER(15,2),
    CURRENCY VARCHAR(3),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
    
    -- Metadata columns
    SOURCE_FILE_NAME               VARCHAR(500),
    SOURCE_FILE_ROW_NUMBER         NUMBER,
    FILE_CONTENT_KEY               VARCHAR(500),
    FILE_LAST_MODIFIED_TIMESTAMP   TIMESTAMP_NTZ,
    LOAD_TIMESTAMP                 TIMESTAMP_NTZ,
    LOAD_SOURCE                    VARCHAR(100)
	);

-->> FUND_HOLDINGS

CREATE OR REPLACE TRANSIENT TABLE POSTGRES_RAW.FUND_HOLDINGS 
	(
    HOLDING_ID NUMBER AUTOINCREMENT,
    ACCOUNT_ID NUMBER,
    FUND_ID NUMBER,
    UNITS_HELD NUMBER(15,4),
    AVERAGE_COST_PER_UNIT NUMBER(15,4),
    CURRENT_VALUE NUMBER(15,2),
    LAST_TRANSACTION_DATE DATE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
    
    -- Metadata columns
    SOURCE_FILE_NAME               VARCHAR(500),
    SOURCE_FILE_ROW_NUMBER         NUMBER,
    FILE_CONTENT_KEY               VARCHAR(500),
    FILE_LAST_MODIFIED_TIMESTAMP   TIMESTAMP_NTZ,
    LOAD_TIMESTAMP                 TIMESTAMP_NTZ,
    LOAD_SOURCE                    VARCHAR(100)
	);

-->> TRANSACTIONS

CREATE OR REPLACE TRANSIENT TABLE POSTGRES_RAW.TRANSACTIONS 
	(
    TRANSACTION_ID NUMBER AUTOINCREMENT,
    TRANSACTION_NUMBER VARCHAR(30),
    ACCOUNT_ID NUMBER,
    FUND_ID NUMBER,
    TRANSACTION_TYPE VARCHAR(20),
    TRANSACTION_DATE DATE,
    SETTLEMENT_DATE DATE,
    UNITS NUMBER(15,4),
    PRICE_PER_UNIT NUMBER(15,4),
    AMOUNT NUMBER(15,2),
    FEES NUMBER(15,2),
    TAX_AMOUNT NUMBER(15,2),
    NET_AMOUNT NUMBER(15,2),
    TRANSACTION_STATUS VARCHAR(20),
    CHANNEL VARCHAR(20),
    NOTES VARCHAR,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
    
    -- Metadata columns
    SOURCE_FILE_NAME               VARCHAR(500),
    SOURCE_FILE_ROW_NUMBER         NUMBER,
    FILE_CONTENT_KEY               VARCHAR(500),
    FILE_LAST_MODIFIED_TIMESTAMP   TIMESTAMP_NTZ,
    LOAD_TIMESTAMP                 TIMESTAMP_NTZ,
    LOAD_SOURCE                    VARCHAR(100)
	);

-->> ACCOUNT_BALANCES

CREATE OR REPLACE TRANSIENT TABLE POSTGRES_RAW.ACCOUNT_BALANCES 
	(
    BALANCE_ID NUMBER AUTOINCREMENT,
    ACCOUNT_ID NUMBER,
    BALANCE_DATE DATE,
    OPENING_BALANCE NUMBER(15,2),
    CLOSING_BALANCE NUMBER(15,2),
    NET_DEPOSITS NUMBER(15,2),
    NET_WITHDRAWALS NUMBER(15,2),
    NET_INVESTMENT_GAIN NUMBER(15,2),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
    
    -- Metadata columns
    SOURCE_FILE_NAME               VARCHAR(500),
    SOURCE_FILE_ROW_NUMBER         NUMBER,
    FILE_CONTENT_KEY               VARCHAR(500),
    FILE_LAST_MODIFIED_TIMESTAMP   TIMESTAMP_NTZ,
    LOAD_TIMESTAMP                 TIMESTAMP_NTZ,
    LOAD_SOURCE                    VARCHAR(100)
	);

-------------------------------
-->> LANDING TABLES FROM GCS
-------------------------------

USE SCHEMA GCS_RAW

-->> FUND METADATA, CSV SOURCE

CREATE OR REPLACE TRANSIENT TABLE GCS_RAW.FUND_METADATA 
	(
    FUND_CODE               VARCHAR(20),
    FUND_NAME               VARCHAR(200),
    FUND_CATEGORY           VARCHAR(50),
    INCEPTION_DATE          DATE,
    MANAGER_NAME            VARCHAR(100),
    INVESTMENT_OBJECTIVE    VARCHAR,
    MINIMUM_INVESTMENT      NUMBER(12,2),
    DIVIDEND_FREQUENCY      VARCHAR(50),
    RISK_RATING             VARCHAR(20),
    TAX_TREATMENT           VARCHAR(50),
    
      -- Metadata columns
    
    SOURCE_FILE_NAME               VARCHAR(500),
    SOURCE_FILE_ROW_NUMBER         NUMBER,
    FILE_CONTENT_KEY               VARCHAR(500),
    FILE_LAST_MODIFIED_TIMESTAMP   TIMESTAMP_NTZ,
    LOAD_TIMESTAMP                 TIMESTAMP_NTZ,
    LOAD_SOURCE                    VARCHAR(100)
	);

--->> NAV_DATA, CSV SOURCE

CREATE OR REPLACE TRANSIENT TABLE GCS_RAW.NAV_DATA 
	(
    DATE                DATE,
    FUND_CODE           VARCHAR(20),
    FUND_NAME           VARCHAR(200),
    NAV                 NUMBER(18,4),
    CHANGE_PERCENT      NUMBER(6,2),
    TOTAL_ASSETS        NUMBER(20,2),
    
    -- Metadata columns
    
    SOURCE_FILE_NAME               VARCHAR(500),
    SOURCE_FILE_ROW_NUMBER         NUMBER,
    FILE_CONTENT_KEY               VARCHAR(500),
    FILE_LAST_MODIFIED_TIMESTAMP   TIMESTAMP_NTZ,
    LOAD_TIMESTAMP                 TIMESTAMP_NTZ,
    LOAD_SOURCE                    VARCHAR(100)
	);

--->> MARKET DATA (RAW JSON)
    
CREATE OR REPLACE TRANSIENT TABLE GCS_RAW.MARKET_DATA_RAW_JSON
	(
    JSON_CONTENT                    OBJECT, 
    
     -- Metadata columns
    SOURCE_FILE_NAME                VARCHAR,
    SOURCE_FILE_ROW_NUMBER          NUMBER,
    FILE_CONTENT_KEY                VARCHAR,
    FILE_LAST_MODIFIED_TIMESTAMP    TIMESTAMP_LTZ,
    LOAD_TIMESTAMP                  TIMESTAMP_LTZ,
    LOAD_SOURCE                     VARCHAR
	);


--->> RATINGS (RAW JSON)

CREATE OR REPLACE TRANSIENT TABLE GCS_RAW.RATINGS_DATA_RAW_JSON
	(
    JSON_CONTENT                    OBJECT, 
    
    -- Metadata columns
    SOURCE_FILE_NAME                VARCHAR,
    SOURCE_FILE_ROW_NUMBER          NUMBER,
    FILE_CONTENT_KEY                VARCHAR,
    FILE_LAST_MODIFIED_TIMESTAMP    TIMESTAMP_LTZ,
    LOAD_TIMESTAMP                  TIMESTAMP_LTZ,
    LOAD_SOURCE                     VARCHAR
	);

--==============================
-- VARIFYING TABLES
--==============================

USE SCHEMA GCS_RAW;

SHOW TABLES;

--==============================
-- END OF THE DOCUMENT
--==============================