
USE DATABASE FINANCE_DB;

--==============================
-- SHOW TABLES
--==============================

USE SCHEMA GCS_RAW;

SHOW TABLES;

--==============================
-- CREATE DYNAMIC TABLES
--==============================

-->> MARKET DATA, FROM RAW JSON TABLE

CREATE OR REPLACE TRANSIENT DYNAMIC TABLE GCS_RAW.MARKET_DATA
TARGET_LAG = DOWNSTREAM 
WAREHOUSE = POC_DYNAMIC_TABLE_WAREHOUSE
AS 
(
SELECT 

	MAIN.JSON_CONTENT:date::DATE AS "DATE",	
	F_OBJECT.KEY::TEXT AS INDEX_NAME,
	F_OBJECT.VALUE:ticker::TEXT AS TICKER,
	F_OBJECT.VALUE:value::NUMBER(18,4) AS VALUE,
	F_OBJECT.VALUE:change_percent::NUMBER(6,2) AS CHANGE_PERCENT,
	F_OBJECT.VALUE:note::VARCHAR(200) AS NOTE,
	
	-- metadata columns
	MAIN.SOURCE_FILE_NAME,	
	MAIN.SOURCE_FILE_ROW_NUMBER,	
	MAIN.FILE_CONTENT_KEY,	
	MAIN.FILE_LAST_MODIFIED_TIMESTAMP,	
	MAIN.LOAD_TIMESTAMP,
	MAIN.LOAD_SOURCE

FROM GCS_RAW.MARKET_DATA_RAW_JSON AS MAIN,
	 LATERAL FLATTEN(INPUT=> MAIN.JSON_CONTENT:indices) AS F_OBJECT
);

--

SELECT * FROM GCS_RAW.MARKET_DATA


-->> MARKET DATA, FROM RAW JSON TABLE

CREATE OR REPLACE TRANSIENT DYNAMIC TABLE GCS_RAW.RATINGS_DATA
TARGET_LAG = DOWNSTREAM 
WAREHOUSE = POC_DYNAMIC_TABLE_WAREHOUSE
AS 
(
SELECT 

	MAIN.$1:report_date::DATE AS REPORT_DATE,
    MAIN.$1:vendor::VARCHAR(100) AS VENDOR,
    JSON_CONTENT.VALUE:fund_code::VARCHAR(20) AS FUND_CODE,
    JSON_CONTENT.VALUE:fund_name::VARCHAR(100) AS FUND_NAME,
    JSON_CONTENT.VALUE:overall_rating::INTEGER AS OVERALL_RATING,
    JSON_CONTENT.VALUE:risk_score::NUMBER(5,2) AS RISK_SCORE,
    JSON_CONTENT.VALUE:return_score::NUMBER(5,2) AS RETURN_SCORE,
    JSON_CONTENT.VALUE:expense_score::NUMBER(5,2) AS EXPENSE_SCORE,
    JSON_CONTENT.VALUE:category_rank::INTEGER AS CATEGORY_RANK,
    JSON_CONTENT.VALUE:analyst_outlook::VARCHAR(20) AS ANALYST_OUTLOOK,
    
	-- metadata columns
	MAIN.SOURCE_FILE_NAME,	
	MAIN.SOURCE_FILE_ROW_NUMBER,	
	MAIN.FILE_CONTENT_KEY,	
	MAIN.FILE_LAST_MODIFIED_TIMESTAMP,	
	MAIN.LOAD_TIMESTAMP,
	MAIN.LOAD_SOURCE

FROM GCS_RAW.MARKET_DATA_RAW_JSON AS MAIN,
    LATERAL FLATTEN(INPUT => MAIN.$1:ratings) AS JSON_CONTENT
);


--==============================
-- END OF THE DOCUMENTS
--==============================

USE SCHEMA GCS_RAW;

SHOW DYNAMIC TABLES;

--==============================
-- END OF THE DOCUMENTS
--==============================
