
USE DATABASE FINANCE_DB;

--==============================
-- SEE ALL FILE FORMATES
--==============================

SHOW FILE FORMATS

--==============================
-- CREATE THE FILE FORMATS
--==============================

-- POSTGRES RAW TABLES

CREATE OR REPLACE FILE FORMAT POSTGRES_RAW.TABLES_PARQUET_FORMAT
TYPE = PARQUET;

-- GCS CSV TABLES

CREATE OR REPLACE FILE FORMAT GCS_RAW.CSV_FORMAT
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 1;

-- GCS JSON TABLES

CREATE OR REPLACE FILE FORMAT GCS_RAW.JSON_FORMAT
TYPE = JSON

--==============================
-- VERIFY FILE FORMATS
--==============================

USE SCHEMA POSTGRES_RAW;

SHOW FILE FORMATS;

USE SCHEMA GCS_RAW;

SHOW FILE FORMATS;
