
USE DATABASE FINANCE_DB;

USE SCHEMA POSTGRES_RAW;

--==============================
-- SEE ALL STORAGE INTEGRATIONS
--==============================

SHOW STAGES

--==============================
-- CREATESTORAGE INTEGRATIONS
--==============================

-- DROP STAGE POSTGRES_RAW.MELTANO_STAGIING_STAGE

CREATE OR REPLACE STAGE POSTGRES_RAW.MELTANO_STAGING_STAGE
FILE_FORMAT = POSTGRES_RAW.POSTGRES_RAW_TABLES_CSV_FORMAT
STORAGE_INTEGRATION = MELTANO_STAGING_STORAGE_INT
URL = 'gcs://finance-data-landing-bucket-poc/meltano-staging'

--

SELECT CURRENT_DATABASE(), CURRENT_SCHEMA()

SHOW STAGES

LIST @POSTGRES_RAW.MELTANO_STAGING_STAGE

SELECT COUNT(*) 
FROM @POSTGRES_RAW.MELTANO_STAGIING_STAGE

--==============================
-- END OF THE DOCUMENT
--==============================