
USE DATABASE FINANCE_DB;

USE SCHEMA POSTGRES_RAW;

--==============================
-- SEE ALL STORAGE INTEGRATIONS
--==============================

SHOW STAGES

--==============================
-- CREATESTORAGE INTEGRATIONS
--==============================

-->> MELTANO STAGING

CREATE OR REPLACE STAGE POSTGRES_RAW.MELTANO_STAGING_STAGE
FILE_FORMAT = POSTGRES_RAW.POSTGRES_RAW_TABLES_CSV_FORMAT
STORAGE_INTEGRATION = GCS_FINANCE_DATA_LANDING_STORAGE_INT
URL = 'gcs://finance-data-landing-bucket-poc/meltano-staging';

LIST @POSTGRES_RAW.MELTANO_STAGING_STAGE


-->> FUND METADATA

USE SCHEMA GCS_RAW;

CREATE OR REPLACE STAGE GCS_RAW.FUND_METADATA_STAGE
FILE_FORMAT = GCS_RAW.CSV_FORMAT
STORAGE_INTEGRATION = GCS_FINANCE_DATA_LANDING_STORAGE_INT
URL = 'gcs://finance-data-landing-bucket-poc/fund-metadata';

LIST @GCS_RAW.FUND_METADATA_STAGE;


-->> MARKET DATA

USE SCHEMA GCS_RAW;

CREATE OR REPLACE STAGE GCS_RAW.MARKET_DATA_STAGE
FILE_FORMAT = GCS_RAW.JSON_FORMAT
STORAGE_INTEGRATION = GCS_FINANCE_DATA_LANDING_STORAGE_INT
URL = 'gcs://finance-data-landing-bucket-poc/market-data';

LIST @GCS_RAW.MARKET_DATA_STAGE;


-->> NAV DATA

USE SCHEMA GCS_RAW;

CREATE OR REPLACE STAGE GCS_RAW.NAV_DATA_STAGE
FILE_FORMAT = GCS_RAW.CSV_FORMAT
STORAGE_INTEGRATION = GCS_FINANCE_DATA_LANDING_STORAGE_INT
URL = 'gcs://finance-data-landing-bucket-poc/nav-data';

LIST @GCS_RAW.NAV_DATA_STAGE;


-->> RATINGS DATA

USE SCHEMA GCS_RAW;

CREATE OR REPLACE STAGE GCS_RAW.RATINGS_DATA_STAGE
FILE_FORMAT = GCS_RAW.JSON_FORMAT
STORAGE_INTEGRATION = GCS_FINANCE_DATA_LANDING_STORAGE_INT
URL = 'gcs://finance-data-landing-bucket-poc/ratings-data';

LIST @GCS_RAW.RATINGS_DATA_STAGE;

--

USE SCHEMA GCS_RAW;

SHOW STAGES;

USE SCHEMA POSTGRES_RAW;

SHOW STAGES;

--==============================
-- END OF THE DOCUMENT
--==============================