
USE DATABASE FINANCE_DB;

USE SCHEMA POSTGRES_RAW;

--==============================
-- SEE ALL STORAGE INTEGRATIONS
--==============================

SHOW STAGES

--============================================
-- CREATE EXTERNAL STAGINGS FOR POSTGRES_RAW
--============================================

-->> POSTGRES - ACCOUNTS

USE SCHEMA POSTGRES_RAW;

CREATE OR REPLACE STAGE POSTGRES_RAW.ACCOUNTS_STAGE
FILE_FORMAT = POSTGRES_RAW.TABLES_PARQUET_FORMAT
STORAGE_INTEGRATION = GCS_FINANCE_DATA_LANDING_STORAGE_INT
URL = 'gcs://finance-data-landing-bucket-poc/trino-extracts/accounts';

LIST @POSTGRES_RAW.ACCOUNTS_STAGE;


-->> POSTGRES - ACCOUNT BALANCES

USE SCHEMA POSTGRES_RAW;

CREATE OR REPLACE STAGE POSTGRES_RAW.ACCOUNT_BALANCES_STAGE
FILE_FORMAT = POSTGRES_RAW.TABLES_PARQUET_FORMAT
STORAGE_INTEGRATION = GCS_FINANCE_DATA_LANDING_STORAGE_INT
URL = 'gcs://finance-data-landing-bucket-poc/trino-extracts/account_balances';

LIST @POSTGRES_RAW.ACCOUNT_BALANCES_STAGE;


-->> POSTGRES - FUND HOLDINGS

USE SCHEMA POSTGRES_RAW;

CREATE OR REPLACE STAGE POSTGRES_RAW.FUND_HOLDINGS_STAGE
FILE_FORMAT = POSTGRES_RAW.TABLES_PARQUET_FORMAT
STORAGE_INTEGRATION = GCS_FINANCE_DATA_LANDING_STORAGE_INT
URL = 'gcs://finance-data-landing-bucket-poc/trino-extracts/fund_holdings';

LIST @POSTGRES_RAW.FUND_HOLDINGS_STAGE;

--========================================
-- CREATE EXTERNAL STAGINGS FOR GCS_RAW
--=======================================

-->> FUND METADATA

USE SCHEMA GCS_RAW;

CREATE OR REPLACE STAGE GCS_RAW.FUND_METADATA_STAGE
FILE_FORMAT = GCS_RAW.CSV_FORMAT
STORAGE_INTEGRATION = GCS_FINANCE_DATA_LANDING_STORAGE_INT
URL = 'gcs://finance-data-landing-bucket-poc/fund-metadata';

LIST @GCS_RAW.FUND_METADATA_STAGE;


-->> MARKET DATA

USE SCHEMA GCS_RAW;

CREATE OR REPLACE STAGE GCS_RAW.MARKET_DATA_STAGE
FILE_FORMAT = GCS_RAW.JSON_FORMAT
STORAGE_INTEGRATION = GCS_FINANCE_DATA_LANDING_STORAGE_INT
URL = 'gcs://finance-data-landing-bucket-poc/market-data';

LIST @GCS_RAW.MARKET_DATA_STAGE;


-->> NAV DATA

USE SCHEMA GCS_RAW;

CREATE OR REPLACE STAGE GCS_RAW.NAV_DATA_STAGE
FILE_FORMAT = GCS_RAW.CSV_FORMAT
STORAGE_INTEGRATION = GCS_FINANCE_DATA_LANDING_STORAGE_INT
URL = 'gcs://finance-data-landing-bucket-poc/nav-data';

LIST @GCS_RAW.NAV_DATA_STAGE;


-->> RATINGS DATA

USE SCHEMA GCS_RAW;

CREATE OR REPLACE STAGE GCS_RAW.RATINGS_DATA_STAGE
FILE_FORMAT = GCS_RAW.JSON_FORMAT
STORAGE_INTEGRATION = GCS_FINANCE_DATA_LANDING_STORAGE_INT
URL = 'gcs://finance-data-landing-bucket-poc/ratings-data';

LIST @GCS_RAW.RATINGS_DATA_STAGE;

--

USE SCHEMA GCS_RAW;

SHOW STAGES;

USE SCHEMA POSTGRES_RAW;

SHOW STAGES;

--==============================
-- END OF THE DOCUMENT
--==============================