
USE DATABASE FINANCE_DB;

--==============================
-- SHOW ALL PIPES
--==============================

USE SCHEMA GCS_RAW;

SHOW PIPES;

--==============================
-- SHOW ALL PIPES
--==============================

-->> FUND METADATA PIPE CSV FILES

CREATE OR REPLACE PIPE GCS_RAW.FUND_METADATA_PIPE 
INTEGRATION = GCS_FINANCE_DATA_LANDING_NOTIFICATION_INT
AUTO_INGEST = TRUE
AS
COPY INTO GCS_RAW.FUND_METADATA 
FROM 
(
SELECT
    $1::VARCHAR(20)        AS FUND_CODE,
    $2::VARCHAR(200)       AS FUND_NAME,
    $3::VARCHAR(50)        AS FUND_CATEGORY,
    $4::DATE               AS INCEPTION_DATE,
    $5::VARCHAR(100)       AS MANAGER_NAME,
    $6::VARCHAR            AS INVESTMENT_OBJECTIVE,
    $7::NUMBER(12,2)       AS MINIMUM_INVESTMENT,
    $8::VARCHAR(50)        AS DIVIDEND_FREQUENCY,
    $9::VARCHAR(20)        AS RISK_RATING,
    $10::VARCHAR(50)       AS TAX_TREATMENT,
    --
	METADATA$FILENAME      		AS SOURCE_FILE_NAME,
	METADATA$FILE_ROW_NUMBER 	AS SOURCE_FILE_ROW_NUMBER,
	METADATA$FILE_CONTENT_KEY 	AS FILE_CONTENT_KEY,
	METADATA$FILE_LAST_MODIFIED AS FILE_LAST_MODIFIED_TIMESTAMP,
	CURRENT_TIMESTAMP()    		AS LOAD_TIMESTAMP,
    'PIPE' 						AS LOAD_SOURCE

FROM @GCS_RAW.FUND_METADATA_STAGE
)
PATTERN = '.*fund-metadata.*\.csv';

--

LIST @GCS_RAW.FUND_METADATA_STAGE

ALTER PIPE GCS_RAW.FUND_METADATA_PIPE REFRESH;

SELECT TOP 10 * FROM GCS_RAW.FUND_METADATA

SELECT SYSTEM$PIPE_STATUS('GCS_RAW.FUND_METADATA_PIPE');



-->> NAV DATA PIPE , CSV FILES

CREATE OR REPLACE PIPE GCS_RAW.NAV_DATA_PIPE 
INTEGRATION = GCS_FINANCE_DATA_LANDING_NOTIFICATION_INT
AUTO_INGEST = TRUE
AS
COPY INTO GCS_RAW.NAV_DATA 
FROM 
(
SELECT
    $1::DATE       		AS 	DATE,
    $2::VARCHAR(20) 	AS	FUND_CODE,
    $3::VARCHAR(200)	AS 	FUND_NAME,
    $4::NUMBER(18,4)	AS 	NAV,
    $5::NUMBER(6,2)		AS 	CHANGE_PERCENT,
    $6::NUMBER(20,2) 	AS 	TOTAL_ASSETS,
    --
	METADATA$FILENAME      		AS SOURCE_FILE_NAME,
	METADATA$FILE_ROW_NUMBER 	AS SOURCE_FILE_ROW_NUMBER,
	METADATA$FILE_CONTENT_KEY 	AS FILE_CONTENT_KEY,
	METADATA$FILE_LAST_MODIFIED AS FILE_LAST_MODIFIED_TIMESTAMP,
	CURRENT_TIMESTAMP()    		AS LOAD_TIMESTAMP,
    'PIPE' 						AS LOAD_SOURCE

FROM @GCS_RAW.NAV_DATA_STAGE
)
PATTERN = '.*nav-data.*\.csv';

--

LIST @GCS_RAW.NAV_DATA_STAGE

ALTER PIPE GCS_RAW.NAV_DATA_PIPE REFRESH;

SELECT TOP 10 * FROM GCS_RAW.NAV_DATA

SELECT SYSTEM$PIPE_STATUS('GCS_RAW.NAV_DATA_PIPE');


-->> MARKET_DATA PIPE (RAW JSON)

CREATE OR REPLACE PIPE GCS_RAW.MARKET_DATA_PIPE 
INTEGRATION = GCS_FINANCE_DATA_LANDING_NOTIFICATION_INT
AUTO_INGEST = TRUE
AS
COPY INTO GCS_RAW.MARKET_DATA_RAW_JSON 
FROM 
(
SELECT 
	$1 AS JSON_CONTENT,
	
	-- MetaData Columsn	
	METADATA$FILENAME      		AS SOURCE_FILE_NAME,
	METADATA$FILE_ROW_NUMBER 	AS SOURCE_FILE_ROW_NUMBER,
	METADATA$FILE_CONTENT_KEY 	AS FILE_CONTENT_KEY,
	METADATA$FILE_LAST_MODIFIED AS FILE_LAST_MODIFIED_TIMESTAMP,
	CURRENT_TIMESTAMP()    		AS LOAD_TIMESTAMP,
    'PIPE' 						AS LOAD_SOURCE
    
FROM @GCS_RAW.MARKET_DATA_STAGE
)
PATTERN = '.*market-data.*\.csv';

--

LIST @GCS_RAW.NAV_DATA_STAGE

ALTER PIPE GCS_RAW.NAV_DATA_PIPE REFRESH;

SELECT TOP 10 * FROM GCS_RAW.MARKET_DATA_RAW_JSON

SELECT SYSTEM$PIPE_STATUS('GCS_RAW.MARKET_DATA_PIPE');


-->> RATINGS DATA 

CREATE OR REPLACE PIPE GCS_RAW.RATINGS_DATA_PIPE 
INTEGRATION = GCS_FINANCE_DATA_LANDING_NOTIFICATION_INT
AUTO_INGEST = TRUE
AS
COPY INTO GCS_RAW.RATINGS_DATA_RAW_JSON 
FROM 
(
SELECT 
	$1 AS JSON_CONTENT,
	
	-- MetaData Columsn	
	METADATA$FILENAME      		AS SOURCE_FILE_NAME,
	METADATA$FILE_ROW_NUMBER 	AS SOURCE_FILE_ROW_NUMBER,
	METADATA$FILE_CONTENT_KEY 	AS FILE_CONTENT_KEY,
	METADATA$FILE_LAST_MODIFIED AS FILE_LAST_MODIFIED_TIMESTAMP,
	CURRENT_TIMESTAMP()    		AS LOAD_TIMESTAMP,
    'PIPE' 						AS LOAD_SOURCE
    
FROM @GCS_RAW.RATINGS_DATA_STAGE
)
PATTERN = '.*ratings-data.*\.csv';

--

LIST @GCS_RAW.RATINGS_DATA_STAGE

ALTER PIPE GCS_RAW.RATINGS_DATA_PIPE REFRESH;

SELECT TOP 10 * FROM GCS_RAW.RATINGS_DATA_RAW_JSON

SELECT SYSTEM$PIPE_STATUS('GCS_RAW.RATINGS_DATA_PIPE');

--==============================
-- END OF THE DOCUMENT
--==============================









