FROM apache/airflow:2.8.1

USER airflow

RUN pip install --no-cache-dir \
    apache-airflow-providers-trino==5.7.1 \
    apache-airflow-providers-snowflake==5.3.1 \
    trino==0.328.0 \
    snowflake-connector-python==3.7.0

USER root