FROM apache/airflow:2.8.1

USER root

RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER airflow

# Install packages including Docker provider
RUN pip install --no-cache-dir \
    apache-airflow-providers-trino==5.7.1 \
    apache-airflow-providers-snowflake==5.3.1 \
    apache-airflow-providers-google==10.15.0 \
    apache-airflow-providers-docker==3.7.0 \
    trino==0.328.0 \
    snowflake-connector-python==3.7.0 \
    astronomer-cosmos==1.4.0 \
    google-cloud-storage==2.14.0