name: 'finance_analytics'
version: '1.0.0'
config-version: 2

profile: 'finance_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  finance_analytics:
    # Staging layer - Clean, typed, 1:1 with sources
    staging:
      +materialized: table
      +schema: staging
      +tags: ["staging"]
    
    # Intermediate layer - Business logic
    intermediate:
      +materialized: table
      +schema: intermediate
      +tags: ["intermediate"]
    
    # Marts layer - Analytics-ready
    marts:
      +materialized: table
      +tags: ["marts"]
      finance:
        +schema: analytics
      analytics:
        +schema: analytics

seeds:
  finance_analytics:
    +schema: staging
    +tags: ["seed"]

snapshots:
  finance_analytics:
    +target_schema: snapshots
    +tags: ["snapshot"]